version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/memgraph_addon/graphql"
      - "/tests/browser"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/memgraph_addon"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/memgraph-platform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
