# MAQA GitHub Projects Configuration — generated 2026-08-25T11:45:18+04:00
owner: "hannovdm"
project_number: "1"
project_id: "PVT_kwHOAadTYs4BhC7W"
status_field_id: "PVTSSF_lAHOAadTYs4BhC7WzhgAMHg"
todo_option_id: "700bf371"
in_progress_option_id: "47fc9ee4"
in_review_option_id: "8bee89f7"
done_option_id: "98236657"
linked_repo: ""
